@startuml vision-id-class
class GUI {
    void chooseAnalyzer(type: int)
    image generateFrame(img: image)
    void addFace(img: image, name: str)
}

class Analyzer {
    {static} KNOWN_FACES_DIR: str
    image analyzeFrame(img: image)
}

class Draw {
    image draw(img: image, tl: tuple, br: tuple)
}

class ImageAnalyzer {
    image analyzeImage(img: image)
}
class VideoAnalyzer {
    void analyzeVideo(vid: str)
}
class LiveAnalyzer {
    void analyzeStream(src: int)
}

GUI o-- ImageAnalyzer
GUI o-- VideoAnalyzer
GUI o-- LiveAnalyzer

Analyzer o- Draw

ImageAnalyzer o-- Analyzer
VideoAnalyzer o-- Analyzer
LiveAnalyzer o-- Analyzer

@enduml