@startuml live-sequence

actor User
activate User
activate GUI

User -> GUI : stream(source)

GUI -> LiveAnalyzer : analyzeStream(source)
activate LiveAnalyzer

loop analysis type = live
    LiveAnalyzer -> Analyzer : analyzeFrame(image)
    activate Analyzer
    Analyzer -> Draw : draw(image, name, tl, br)
    note left: tl: Top Left, br: Bottom Right
    activate Draw
    Draw -> Analyzer : newImage()
    deactivate Draw
    Analyzer -> LiveAnalyzer : newImage()
    deactivate Analyzer
    LiveAnalyzer -> GUI : newImage()
    deactivate LiveAnalyzer
    GUI -> User : displayImage()

    opt
        User -> GUI : pauseStream()
        User -> GUI : addFace(name)
        GUI -> GUI : addKnownFace(image, name)
        GUI -> User : response(status)
    end
end

@enduml