@startuml video-sequence

actor User
activate User
activate GUI

alt video analysis
    User -> GUI : select video
    GUI -> VideoAnalyzer : load_video(video)
else live analysis
    User -> GUI : select live
    GUI -> VideoAnalyzer : load_live(feed)
end

activate VideoAnalyzer

User -> GUI: play
GUI -> VideoAnalyzer: start_analyzing(display)

loop video/stream duration
    
    VideoAnalyzer -> Analyzer : analyze_frame(image)
    activate Analyzer
    Analyzer -> Draw : draw(image, name, tl, br)
    note left: tl: Top Left, br: Bottom Right
    activate Draw
    Draw --> Analyzer
    deactivate Draw
    Analyzer --> VideoAnalyzer
    deactivate Analyzer
    VideoAnalyzer -> GUI: update_display(image)

    opt
        User -> GUI : pause
        User -> GUI : add face
        GUI -> GUI : add_face(name)
    end
end

@enduml