@startuml image-sequence

actor User
activate User
activate GUI

User -> GUI : uploadImage(imageFile)
GUI -> User : promptSelection()

opt image analysis
    User -> GUI : analyzeImage()
    GUI -> ImageAnalyzer : analyzeImage(image)
    activate ImageAnalyzer
    ImageAnalyzer -> Analyzer : analyzeFrame(image)
    activate Analyzer
    Analyzer -> ImageAnalyzer : info(name, tl, br)
    deactivate Analyzer
    
    ImageAnalyzer -> Draw : draw(image, name, tl, br)
    note left: tl: Top Left, br: Bottom Right
    activate Draw
    Draw -> ImageAnalyzer : newImage()
    deactivate Draw
    ImageAnalyzer -> GUI : newImage()
    deactivate 
    GUI -> User : displayImage()
end

opt add known face
    User -> GUI : addFace(name)
    GUI -> GUI : addKnownFace(image, name)
    GUI -> User : response(status)
end

@enduml